### PR TITLE
1-Test Support methods

### PR DESCRIPTION
**Pull request by leonardk1**
As a way of reusing Code some two methods from a recent project(Oily)
That were used to DRY up code have been added here to perform the work
they used to perform

#### task
- [x] Add Support Methods in the Test Environment

### CODE REVIEW

**Comment by leonardk1** [comment]
@godfreym please review

**Comment by godfreym** [comment]
@leonardk1 :+1:

**Comment by leonardk1** [comment]
@godfreym added one more line

**Comment by leonardk1** [comment]
@arafatm please review

**Comment by leonardk1** [comment]
@godfreym there is one more line added to this PR

**Comment by godfreym** [comment]
@leonardk1 :+1:

**Comment by arafatm** [comment]
:+1:

**Pull request merged**
