### PR TITLE
12 generate The Entity RelationShip Diagram

### PR DESCRIPTION
**Pull request by leonardk1**
#12
As A developer
I Want To Generate the ERD
So That I Can easily visualize the application model set up

##### Tasks 
- [x] Install Graphviz as shown [here](http://voormedia.github.io/rails-erd/install.html)
     via `sudo apt-get install graphviz`
- [x] add the `rails-erd` gem

### CODE REVIEW

**Comment by leonardk1** [comment]
@godfreym please review

**Comment by godfreym** [comment]
@leonardk1 :+1:

**Comment by leonardk1** [comment]
@arafatm please review

**Comment by arafatm** [comment]
:+1:

**Pull request merged**
