### PR TITLE
1 Setting Up The Product Model

### PR DESCRIPTION
**Pull request by leonardk1**
#1 
As A developer
I Want To Set Up the Product Model
So That I can Develop features related to the Model

#### Tasks
- [x] Create the Product Model
- [x] Associate the Business and Product Models

### CODE REVIEW

**Comment by leonardk1** [comment]
@godfreym please review

**Comment by godfreym** [comment]
@leonardk1 When you do generate model then within the command you specify the attributes, no need of creating a model then generate another migration to add the attributes
i.e in this you could just do `$ rails g model Product name:string unit_price:integer business_id:integer `

**Comment by leonardk1** [comment]
@godfreym I like this other method more, it reduces the chances of me making errors on the command line

**Comment by godfreym** [comment]
@leonardk1 You are repeating yourself, one command 3 commits and you are done with the model setup

**Comment by leonardk1** [comment]
@godfreym Nop I still have some more models

**Comment by godfreym** [comment]
@leonardk1 The point of my comment is, instead of generating 3 migrations, you could have only one migration file which would have done the same job those 3 did
`$ rails g model Product name:string unit_price:integer business_id:integer`

**Comment by leonardk1** [comment]
@godfreym noted will implement those changes in other PRs, but I still haven't seen anywhere in the rails documentation where it is a MUST to use that style

@arafatm please review

**Comment by arafatm** [comment]
:+1:

**Pull request merged**
