### PR TITLE
1 Setting Up the business payment accounts

### PR DESCRIPTION
**Pull request by leonardk1**
#1 
As A developer
I Want to set Up the Business Payment Accounts
So That I can Link Businesses to Their accounts

##### Tasks
- [x] create the bank account and mobile money account models

### CODE REVIEW

**Comment by leonardk1** [comment]
@godfreym please review

**Comment by godfreym** [comment]
@leonardk1 :+1:

**Comment by leonardk1** [comment]
@arafatm please review

**Comment by arafatm** [comment]
:+1:

**Pull request merged**
